// Stub for geo-data — the full dataset is generated by a parallel agent.
// This file will be replaced with the real data when that agent completes.

export const REGIONI: string[] = [
  "Abruzzo",
  "Basilicata",
  "Calabria",
  "Campania",
  "Emilia-Romagna",
  "Friuli-Venezia Giulia",
  "Lazio",
  "Liguria",
  "Lombardia",
  "Marche",
  "Molise",
  "Piemonte",
  "Puglia",
  "Sardegna",
  "Sicilia",
  "Toscana",
  "Trentino-Alto Adige",
  "Umbria",
  "Valle d'Aosta",
  "Veneto",
]

export interface ProvinciaInfo {
  codice: string
  nome: string
}

export const PROVINCE_BY_REGIONE: Record<string, ProvinciaInfo[]> = {
  "Abruzzo": [
    { codice: "AQ", nome: "L'Aquila" },
    { codice: "CH", nome: "Chieti" },
    { codice: "PE", nome: "Pescara" },
    { codice: "TE", nome: "Teramo" },
  ],
  "Basilicata": [
    { codice: "MT", nome: "Matera" },
    { codice: "PZ", nome: "Potenza" },
  ],
  "Calabria": [
    { codice: "CZ", nome: "Catanzaro" },
    { codice: "CS", nome: "Cosenza" },
    { codice: "KR", nome: "Crotone" },
    { codice: "RC", nome: "Reggio Calabria" },
    { codice: "VV", nome: "Vibo Valentia" },
  ],
  "Campania": [
    { codice: "AV", nome: "Avellino" },
    { codice: "BN", nome: "Benevento" },
    { codice: "CE", nome: "Caserta" },
    { codice: "NA", nome: "Napoli" },
    { codice: "SA", nome: "Salerno" },
  ],
  "Emilia-Romagna": [
    { codice: "BO", nome: "Bologna" },
    { codice: "FC", nome: "Forlì-Cesena" },
    { codice: "FE", nome: "Ferrara" },
    { codice: "MO", nome: "Modena" },
    { codice: "PC", nome: "Piacenza" },
    { codice: "PR", nome: "Parma" },
    { codice: "RA", nome: "Ravenna" },
    { codice: "RE", nome: "Reggio Emilia" },
    { codice: "RN", nome: "Rimini" },
  ],
  "Friuli-Venezia Giulia": [
    { codice: "GO", nome: "Gorizia" },
    { codice: "PN", nome: "Pordenone" },
    { codice: "TS", nome: "Trieste" },
    { codice: "UD", nome: "Udine" },
  ],
  "Lazio": [
    { codice: "FR", nome: "Frosinone" },
    { codice: "LT", nome: "Latina" },
    { codice: "RI", nome: "Rieti" },
    { codice: "RM", nome: "Roma" },
    { codice: "VT", nome: "Viterbo" },
  ],
  "Liguria": [
    { codice: "GE", nome: "Genova" },
    { codice: "IM", nome: "Imperia" },
    { codice: "SP", nome: "La Spezia" },
    { codice: "SV", nome: "Savona" },
  ],
  "Lombardia": [
    { codice: "BG", nome: "Bergamo" },
    { codice: "BS", nome: "Brescia" },
    { codice: "CO", nome: "Como" },
    { codice: "CR", nome: "Cremona" },
    { codice: "LC", nome: "Lecco" },
    { codice: "LO", nome: "Lodi" },
    { codice: "MB", nome: "Monza e Brianza" },
    { codice: "MI", nome: "Milano" },
    { codice: "MN", nome: "Mantova" },
    { codice: "PV", nome: "Pavia" },
    { codice: "SO", nome: "Sondrio" },
    { codice: "VA", nome: "Varese" },
  ],
  "Marche": [
    { codice: "AN", nome: "Ancona" },
    { codice: "AP", nome: "Ascoli Piceno" },
    { codice: "FM", nome: "Fermo" },
    { codice: "MC", nome: "Macerata" },
    { codice: "PU", nome: "Pesaro e Urbino" },
  ],
  "Molise": [
    { codice: "CB", nome: "Campobasso" },
    { codice: "IS", nome: "Isernia" },
  ],
  "Piemonte": [
    { codice: "AL", nome: "Alessandria" },
    { codice: "AT", nome: "Asti" },
    { codice: "BI", nome: "Biella" },
    { codice: "CN", nome: "Cuneo" },
    { codice: "NO", nome: "Novara" },
    { codice: "TO", nome: "Torino" },
    { codice: "VB", nome: "Verbano-Cusio-Ossola" },
    { codice: "VC", nome: "Vercelli" },
  ],
  "Puglia": [
    { codice: "BA", nome: "Bari" },
    { codice: "BAT", nome: "Barletta-Andria-Trani" },
    { codice: "BR", nome: "Brindisi" },
    { codice: "FG", nome: "Foggia" },
    { codice: "LE", nome: "Lecce" },
    { codice: "TA", nome: "Taranto" },
  ],
  "Sardegna": [
    { codice: "CA", nome: "Cagliari" },
    { codice: "CI", nome: "Carbonia-Iglesias" },
    { codice: "MD", nome: "Medio Campidano" },
    { codice: "NU", nome: "Nuoro" },
    { codice: "OG", nome: "Ogliastra" },
    { codice: "OR", nome: "Oristano" },
    { codice: "OT", nome: "Olbia-Tempio" },
    { codice: "SS", nome: "Sassari" },
    { codice: "VS", nome: "Medio Campidano" },
  ],
  "Sicilia": [
    { codice: "AG", nome: "Agrigento" },
    { codice: "CL", nome: "Caltanissetta" },
    { codice: "CT", nome: "Catania" },
    { codice: "EN", nome: "Enna" },
    { codice: "ME", nome: "Messina" },
    { codice: "PA", nome: "Palermo" },
    { codice: "RG", nome: "Ragusa" },
    { codice: "SR", nome: "Siracusa" },
    { codice: "TP", nome: "Trapani" },
  ],
  "Toscana": [
    { codice: "AR", nome: "Arezzo" },
    { codice: "FI", nome: "Firenze" },
    { codice: "GR", nome: "Grosseto" },
    { codice: "LI", nome: "Livorno" },
    { codice: "LU", nome: "Lucca" },
    { codice: "MS", nome: "Massa-Carrara" },
    { codice: "PI", nome: "Pisa" },
    { codice: "PO", nome: "Prato" },
    { codice: "PT", nome: "Pistoia" },
    { codice: "SI", nome: "Siena" },
  ],
  "Trentino-Alto Adige": [
    { codice: "BZ", nome: "Bolzano" },
    { codice: "TN", nome: "Trento" },
  ],
  "Umbria": [
    { codice: "PG", nome: "Perugia" },
    { codice: "TR", nome: "Terni" },
  ],
  "Valle d'Aosta": [
    { codice: "AO", nome: "Aosta" },
  ],
  "Veneto": [
    { codice: "BL", nome: "Belluno" },
    { codice: "PD", nome: "Padova" },
    { codice: "RO", nome: "Rovigo" },
    { codice: "TV", nome: "Treviso" },
    { codice: "VE", nome: "Venezia" },
    { codice: "VI", nome: "Vicenza" },
    { codice: "VR", nome: "Verona" },
  ],
}

// Minimal stub for comuni — the real file will have full comune lists
export const COMUNI_BY_PROVINCIA: Record<string, string[]> = {}

export function getNomeProvincia(codice: string): string | null {
  for (const province of Object.values(PROVINCE_BY_REGIONE)) {
    const found = province.find(p => p.codice === codice.toUpperCase())
    if (found) return found.nome
  }
  return null
}

export function getRegioneFromCodice(codice: string): string | null {
  for (const [regione, province] of Object.entries(PROVINCE_BY_REGIONE)) {
    if (province.some(p => p.codice === codice.toUpperCase())) return regione
  }
  return null
}
